PREP(addJammer);
PREP(updateJamMarker);
PREP(removeJamMarker);
PREP(jammerPlayerLocal);
PREP(resetTfarIfDegraded);
PREP(isJammerActive);
PREP(actionJamToggle);
PREP(actionJamToggleListener);
PREP(removeJammer);